site_name: Bookkeeper
theme:
  name: material
  language: en
  palette:
    scheme: slate
    primary: lime
    accent: deep purple
  features:
    - header.autohide
    - navigation.tabs
    - navigation.footer
    - search.suggest
    - search.highlight
